-- Verified seed data for the recruitment portal.
-- Official source: UPSC recruitment page and PIB release dated 10 Aug 2026.
-- Advertisement No. 10/2026 covers 34 vacancies across 7 post groups.
-- This seed publishes the individually verified Research Officer post (11 vacancies).

INSERT INTO recruitments (
    id, slug, title, short_title, organisation, department,
    recruitment_category, advertisement_number, description, number_of_posts,
    vacancy_details, state, location, job_type, employment_type,
    minimum_qualification, experience_required, maximum_age, age_as_on_date,
    age_relaxation, pay_level, salary_min, salary_max, salary_description,
    application_start_date, application_last_date, application_mode,
    application_fee, selection_process, written_exam, interview,
    document_verification, official_organisation, official_notification_url,
    official_application_url, official_source_url, source_title,
    source_published_date, source_last_checked, last_verified_at, status,
    meta_title, meta_description, keywords, created_at, updated_at, published_at
) VALUES (
    'upsc-10-2026-research-officer',
    'upsc-research-officer-2026-advt-10',
    'UPSC Research Officer Recruitment 2026 - Advertisement No. 10/2026',
    'UPSC Research Officer 2026',
    'Union Public Service Commission',
    'National Atlas and Thematic Mapping Organisation, Ministry of Science and Technology',
    'Central Government',
    'Advertisement No. 10/2026 | Vacancy No. 26081005208',
    'UPSC Advertisement No. 10/2026 includes 11 Research Officer vacancies in the National Atlas and Thematic Mapping Organisation, Ministry of Science and Technology. Online applications opened on 8 August 2026. For posts other than those under the Administration of UT of Ladakh, the closing date is 28 August 2026 at 18:00 hours. Candidates must verify the complete official advertisement before applying.',
    11,
    'Research Officer: 11 vacancies (UR-07, EWS-01, OBC-02, SC-01; PwBD reservation included as specified in the notice)',
    'West Bengal',
    'Kolkata',
    'Direct Recruitment by Selection',
    'Permanent / General Central Service Group A, Gazetted, Non-Ministerial',
    'Master''s degree in Geography or Geology or Applied Geology or Geoinformatics or Geographical Information System and Remote Sensing or Geomatics or Geospatial Technology from a recognised University or Institute, with the prescribed subject requirement at bachelor''s level as specified in the official advertisement.',
    'Post-specific experience/eligibility conditions apply; candidates must check Advertisement No. 10/2026.',
    35,
    'As specified in Advertisement No. 10/2026',
    'Category-based age relaxation applies as per the official advertisement and Government rules.',
    'Level-10',
    56100,
    177500,
    'Level-10 in the 7th CPC Pay Matrix',
    '2026-08-08',
    '2026-08-28',
    'Online',
    'Rs 25; female, SC, ST and PwBD candidates are exempt as specified by UPSC.',
    'Direct recruitment by selection; interview-based selection, with shortlisting if required by UPSC.',
    0,
    1,
    1,
    'Union Public Service Commission (UPSC)',
    'https://www.upsc.gov.in/recruitment/recruitment-advertisement',
    'https://upsconline.nic.in/ora/',
    'https://www.upsc.gov.in/recruitment/recruitment-advertisement',
    'UPSC Advertisement No. 10/2026; PIB release: Direct Recruitment to various posts in Government of India',
    '2026-08-10',
    '2026-08-26',
    '2026-08-26',
    'published',
    'UPSC Research Officer Recruitment 2026 - 11 Posts | Advt No. 10/2026',
    'UPSC Research Officer Recruitment 2026: 11 vacancies in NATMO, Ministry of Science and Technology. Check eligibility, salary, important dates and apply through the official UPSC portal.',
    'UPSC Research Officer 2026, UPSC Recruitment 2026, Advertisement 10/2026, Government Jobs 2026, Research Officer Jobs, NATMO Recruitment',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
