-- Migration: 004_mpsc_advt_02_2025_assistant_professor
-- Seed MPSC Manipur Advertisement No. 02/2025.
-- Source: https://mpscmanipur.gov.in/Recruitment_Advertisement.html

INSERT OR IGNORE INTO recruitments (
  id, slug, title, short_title, organisation, department, recruitment_category,
  advertisement_number, description, number_of_posts, state, location, job_type,
  employment_type, minimum_qualification, experience_required, minimum_age,
  maximum_age, age_as_on_date, age_relaxation, pay_level, salary_description,
  application_start_date, application_last_date, application_mode, application_fee,
  fee_details, selection_process, written_exam, interview, document_verification,
  official_organisation, official_notification_url, official_application_url,
  official_source_url, source_title, source_published_date, source_last_checked,
  last_verified_at, status, meta_title, meta_description, keywords, published_at
) VALUES (
  'mpsc-manipur-advt-02-2025-assistant-professor',
  'mpsc-manipur-assistant-professor-recruitment-2025-advt-02-2025',
  'MPSC Manipur Assistant Professor Recruitment 2025 – Advertisement No. 02/2025',
  'MPSC Manipur Assistant Professor Recruitment 2025',
  'Manipur Public Service Commission (MPSC)',
  'Higher Education Department, Government of Manipur',
  'State Government',
  '02/2025',
  'Direct recruitment of 419 Assistant Professors in Government Colleges under the Higher Education Department, Manipur, across the disciplines specified in the official advertisement.',
  419,
  'Manipur',
  'Manipur, India',
  'State Government',
  'Permanent / State Government',
  'Master’s degree with at least 55% marks in the concerned/relevant/allied subject, with NET/SET/SLET or applicable UGC exemption as prescribed in the official notification.',
  'Subject-specific eligibility and experience requirements, if any, are governed by the official advertisement and applicable UGC/Manipur rules.',
  21,
  38,
  '2025-12-05',
  'Age relaxation applies as prescribed for eligible reserved categories and other groups under Government of Manipur rules.',
  'PB-3 / Academic Pay Level as prescribed',
  'PB-3 ₹15,600–39,100 plus Academic Grade Pay ₹6,000 (pre-revised), with applicable revised pay rules.',
  '2025-12-15',
  '2026-01-23',
  'Online',
  '₹600 General/OBC; ₹400 SC/ST',
  'Fee exemptions and final fee rules are subject to the official advertisement and subsequent notices.',
  'Shortlisting/academic assessment followed by Interview / Personality Test as prescribed by the notification.',
  0,
  1,
  1,
  'Manipur Public Service Commission (MPSC)',
  'https://mpscmanipur.gov.in/Recruitment_Advertisement.html',
  'https://empsconline.gov.in/Notice.aspx',
  'https://mpscmanipur.gov.in/Recruitment_Advertisement.html',
  'Advt. No. 02/2025 – Direct recruitment of 419 Assistant Professors under Higher Education Department, Manipur',
  '2025-12-05',
  '2026-08-26',
  '2026-08-26',
  'published',
  'MPSC Manipur Assistant Professor Recruitment 2025 | 419 Posts | Advt. No. 02/2025',
  'MPSC Manipur Assistant Professor Recruitment 2025: 419 Assistant Professor vacancies in Government Colleges, with eligibility, dates and official application information.',
  'MPSC Manipur recruitment 2025, Assistant Professor recruitment, Advt 02/2025, Manipur PSC jobs, 419 Assistant Professor vacancies, Higher Education Department Manipur',
  CURRENT_TIMESTAMP
);
